services:
  - type: web
    name: otasuke-ai
    env: static
    repo: https://github.com/ZETTAI-INC/AITUKAERUSTAF
    branch: feature/blue-design-conversion
    region: singapore
    plan: starter
    buildCommand: ""
    staticPublishPath: ./
    autoDeploy: true
